# Generated by Django 3.0.3 on 2020-02-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterplaner', '0002_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='hall',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='hall',
            field=models.CharField(default='HS 1', max_length=20),
        ),
    ]
