# Generated by Django 3.0.3 on 2020-02-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterplaner', '0003_auto_20200223_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='type',
            field=models.IntegerField(choices=[(0, 'Lecture'), (1, 'Exercise')], default=0),
        ),
    ]
